iterative_verifier.go
sharding/filter.go
sharding/sharding.go
sharding/test/joined_tables_test.go
sharding/test/primary_key_table_test.go
sharding/test/trivial_integration_test.go
sharding/testhelpers/unit_test_suite.go
test/iterative_verifier_integration_test.go
test/iterative_verifier_test.go
utils.go
verifier.go

This change helps keep the primary key table in the target database consistent for a longer time period.
For example, for us, we have developers who `JOIN ON` a primary key table in their queries to filter out some data but see unexpected results. This change makes that sort of inconvenience less likely
follow up to: https://github.com/Shopify/shopify/pull/153139
related to: https://github.com/Shopify/pods/issues/259
@Shopify/pods

Sharding: copy primary key tables only at the end of the ferry

---

config.go
ferry.go
throttler.go

Previously, the way we create `*sql.DB` are scattered all over the place and they do the same thing. It make sense to refactor this into `DatabaseConfig`. This means I won't have to write it again in order to wait for the replica to catch up to the master.
This is a precursor to the PR for waiting on replica to catch up to the master writer node.

Refactor sql.DB creation to DatabaseConfig

---

.travis.yml
.travisci/deploy-packagecloud.sh

We need this back ahead of other work being done as our internal applications depend on it.
@Shopify/pods

Deploy packages to Shopify's packagecloud

---

ferry.go
test/wait_until_replica_is_caught_up_to_master_test.go
wait_until_replica_is_caught_up_to_master.go

Cleaning up the code for WaitUntilReplicaIsCaughtUpToMaster:
- Return an error in `Wait` instead of sending directly to `ErrorHandler`.
- Added an option to make replica wait timeout after a certain amount of time.
- Simplified the `Wait` method so we don't need to set a global-ish variable while still preserving some testing capabilities.

Wait Replica cleanup

---

iterative_verifier.go
sharding/config.go
sharding/sharding.go
test/iterative_verifier_test.go

This PR iterates on our previous heuristic for improving cutover phase verification performance for the iterative verifier. Rather than eagerly re-verifying only once to cut down the `reverifyStore` size, keep re-verifying until the overall size of the store does not improve between iterations – with a reasonable static `maxIterations` and a configurable `MaxDowntime` duration which will determine if the Ferry should proceed any further if the cutover phase verification is predicted to surpass that value.
The PR also adds some helpful metrics for having more visibility into long-running Ferries.
@Shopify/pods

Iterative Verifier: keep on re-verifying until store is small enough

---

iterative_verifier.go

Follow up to https://github.com/Shopify/ghostferry/pull/36
This was a subtle bug we overlooked in the original PR.
@Shopify/pods

Iterative Verifier: reset RowCount when flushing reverifyStore

---

sharding/config.go
sharding/sharding.go

Follow up to https://github.com/Shopify/ghostferry/pull/36
For some reason I had thought using `30[s|d|h]` notation is the canonical way of unmarshalling a time.Duration. Guess not 😬 
@pushrax @fw42

sharding: fix duration config 

---

test/lag_throttler_test.go
throttler.go

Sometimes, when the throttler queries the database, the db returns a single row with only a `NULL` column. This is especially true when the query contains aggregation functions like `MAX()`. Currently, this causes the Ferry to fail ungracefully. 
This PR addresses this by keeping the last known throttling state/value when such conditions occur. It also addresses the condition where _no_ rows are returned in the same manner.
@Shopify/pods @shuhaowu

Handle empty throttler results

---

iterative_verifier.go

This is another follow-up to https://github.com/Shopify/ghostferry/pull/36
Unfortunately, due to the difficult-to-test optimization, we missed this very subtle bug in the PR above: 
* Calling `(r ReverifyStore) FlushAndBatchByTable` on `r.reverifyStore` would perform a `r.flushStore()` which then would set the `r.RowCount` field to 0 on a copy of the struct
* Another goroutine calling `(r *ReverifyStore) Add` would not see this update 
* `before` and `after` values for the reverification optimization (see `reverifyUntilStoreIsSmallEnough`) would monotonically increase, rendering the heuristic of "stop when after >= before" useless.
@shopify/pods

FlushAndBatchByTable must be pointer receiver

---

docs/source/tutorialcopydb.rst

Spotted some missing semi-colons that makes the create db .sql script invalid

Add missing ; to tutorial

---

ferry.go
sharding/sharding.go
test/binlog_streamer_test.go
test/ferry_test.go

This allows a ferry to fail early in case the provided target database connection is not writeable. We previously had this check in our application but it makes more sense to perform this check at the Ghostferry level.
@Shopify/pods @shuhaowu

Check if target database is writable before starting ferry

---

ferry.go
sharding/sharding.go
test/binlog_streamer_test.go
test/ferry_test.go
test/race_conditions_integration_test.go

Currently, we allow running our ferries from readonly replica and we require the user to provide the replica's master connection details. Before we `WaitUntilReplicaIsCaughtUpToMaster`, it makes sense to ensure the connection we have is the currently active writer and avoid data loss.
In our current implementation, you can have a scenario where the master writer has been failed over to another db and our perceived master is lagging behind by a few minutes (compared to the actual master) leading to data loss because we don't wait long enough to catch up to the _actual_ master but rather to another replica.
More context in #48
@Shopify/pods @shuhaowu

Abort ferry if master db becomes read-only

---

Gopkg.lock
binlog_streamer.go
test/types_integration_test.go
vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go
vendor/github.com/siddontang/go-mysql/replication/parser.go
vendor/github.com/siddontang/go-mysql/replication/row_event.go
vendor/github.com/siddontang/go-mysql/replication/time.go

https://github.com/siddontang/go-mysql/pull/295 has been merged and thus we have a way to fix the timezone issue causing binlogs to not properly sync over. 
However, the deeper question now is whether or not setting this to UTC will solve the issue. Should we also try to set the mysql session timezone to UTC while executing queries on the target and the source? Or maybe we have to do something else as well?
Fixes #23

TIMESTAMP Timezone fix

---

compression_verifier.go
config.go
sharding/sharding.go

This integrates the work done in #44 into the sharding package for use in the shop mover.
I also realized that after performing delta-copy of joined tables we never verify the copied rows.
@Shopify/pods

Integration of CompressionVerifier into sharding package

---

ferry.go
sharding/sharding.go
utils.go

Follow up to https://github.com/Shopify/ghostferry/pull/51
The rationale for this one is that it's too risky to go into the cutover phase if the target db is read-only anyway. It replaces a call that we previously did on the shop mover side.
@Shopify/pods

sharding: abort if target db becomes readonly before cutover

---

iterative_verifier.go
sharding/config.go
sharding/sharding.go
test/iterative_verifier_integration_test.go
test/iterative_verifier_test.go

**Problem**
Sometimes, it's desirable to intentionally allow ignoring certain columns like `created_at` during verification. This happens most often in tables that share data between tenants.
**But the sharding package only copies tables that have a tenant_id, how can they share data?**
We allow two other types of tables: joined tables and primary key tables. This is exactly where we need to use this feature
**Solution**
It's a fairly simple change to exclude verification of some columns without impacting their copying
@Shopify/pods

iterative verifier: allow ignored columns

---

binlog_streamer.go
copydb/copydb.go
ferry.go
utils.go

As I'm working through the cancellation stuff, I noticed a few things that is wrong. I've been basing all my PRs on these four very small commits, so we might as well review these and merge them into master. This way we'll have an easier way to compare the different approaches of cancellation. 
Notable changes are:
- Removed the onFinishedIterations hack to block if automatic cutover is false. This block is useful if manual cutover is desired (for something like copydb). This also makes the code more "linear" and therefore easier to understand.
- Fixed an issue where a context.WithDeadline is not canceled. This is not really an issue, but it's not recommended practise for go.
- Changed WithRetriesContext to check the context before running the actual method, which could take a long time. …

Minor code cleanup/refactor

---

tlaplus/ghostferry.tla
tlaplus/ghostferry.toolbox/ghostferry___GhostferryPrimaryModel.launch

This is an important component of Ghostferry and thus deserves to be modeled. It also has implications when modeling Ghostferry with interrupt + resume.
In the previous TLA+ model, the binlogs are written directly to the target database as they are read by the BinlogStreamer. In the present model, they are send into a queue. This queue is read by a separate process (BinlogWriter) and written to the target database atomically one at a time. No batch writing (multistatement transaction that we have implemented) is modeled as I believe only the order is important, not how many binlog entries are written in a single atomic operation. 
Checking this new specification on the standard model yields no invariant violations. I also tested that the specification is correct by intentionally writing …

Updated Ghostferry TLA model with BinlogWriter

---

binlog_streamer.go
binlog_writer.go
dml_events.go
sharding/test/copy_filter_test.go
test/binlog_streamer_test.go
test/dml_events_test.go

Since the BinlogWriter is a separate goroutine to the BinlogStreamer, the position that it wrote to is important if we want to interrupt and resume Ghostferry (interrupt saves BinlogWriter position, and resume starts the BinlogStreamer from the BinlogWriter position).
To allow for this, we need to pass the binlog position from the binlog streamer, via the DMLEvent, to the binlog writer. This patch adds BinlogPosition() to DMLEvent to make this possible.

Pass the current BinlogPosition to DMLEvent so BinlogWriter can set lastWrittenBinlogPosition

---

batch_writer.go
binlog_streamer.go
binlog_writer.go
data_iterator.go
error_handler.go
ferry.go
state_tracker.go
status.go
test/data_iterator_test.go

*The code review might look big, but most of it is me moving the DataIteratorState into its own file called StateTracker.*
Instead of having the DataIterator own the state of the Ferry run, Ferry should own the state as it involves both the DataIterator and the BinlogWriter. This means effectively, the DataIterator and the BinlogWriter "notifies" the StateTracker about their progress. 
This PR moves DataIteratorState to a StateTracker managed by the Ferry. However, this centralization does make using the DataIterator/BinlogStreamer independently of the Ferry slightly more difficult. I think this trade off is okay as it makes the state tracking easy to reason about (it's all in one component!). If we need to, we can refactor a little bit to provide some helper methods to use those …

Refactored DataIteratorState to StateTracker for interruptibility

---

Gopkg.lock
batch_writer.go
binlog_streamer.go
binlog_writer.go
config.go
cursor.go
data_iterator.go
ferry.go
iterative_verifier.go
sharding/testhelpers/unit_test_suite.go
state_tracker.go
test/binlog_streamer_test.go
test/data_iterator_test.go
vendor/github.com/siddontang/go-log/log/handler.go
vendor/github.com/siddontang/go-log/log/logger.go

This PR implements the ability to interrupt Ghostferry via SIGTERM/SIGINT. These signals causes the error handler to dump the current state to stdout and panic to terminate the process.
Resume is also implemented: give a SerializedState as the StateToResumeFrom on the Config object and DataIterator will resume via the LastSuccessfulPrimaryKeys, BinlogStreamer will resume via LastWrittenBinlogPosition, and Ferry uses the table schema cache from the SerializedState.
Testing of this will occur in a PR after this, along with the ruby integration test framework, which I'm still iterating on. The code here stands on its own, however.
**Note: this PR does not implement the reconciliation process. This will be in a subsequent PR.** Interestingly, the implementation is currently already "correct" …

Interrupt Ghostferry via signals and resume from SerializedState

---

batch_writer.go
binlog_writer.go

When Ghostferry's writes to the target fails, print out the PK value and the binlog positions into the error for better debugging.

Log PK/binlog position on error

---

binlog_streamer.go

The go-mysql doesn't parse those events, so we can't handle this event.
This should fix the binlog_streamer panic https://github.com/Shopify/ghostferry/issues/79.

skipping replication.GenericEvent

---

batch_writer.go
binlog_writer.go
data_iterator.go
ferry.go
state_tracker.go
status.go
test/go/data_iterator_test.go
test/integration/interrupt_resume_test.rb
test/test_helper.rb

The previous StateTracker can only handle tracking the copy, not the verify. This commit refactors the StateTracker into two distinct stages: the CopyStateTracker and the VerifierStateTracker, along with their
associated SerializableStates (CopySerializableState and VerifySerializableState).
The Ferry is responsible of initializing and passing the correct stages to the correct components. 
Right now, this PR only really implements the CopyStage. The VerifyStage will be implemented as I make the IterativeVerifier interruptible.

Partially refactored StateTracker into two stages: copy and verify

---

dml_events.go
row_batch.go
test/integration/types_test.rb

JSON column was previously being recognized as a []byte array in the BinlogWriter. This causes the INSERT/UPDATE/DELETE query generated to be with something like `_binary'{"data": 1}'`. However, JSON data are not binary, thus MySQL will return errors  errors such as:
> Error 3144: Cannot create a JSON value from a string with CHARACTER SET binary error.
Fixing this requires us to pass the column types into the methods actually escaping the values (`appendEscapedValues`), as we cannot infer that something is a JSON type from the Go type alone. This turned out to be a rather large list of methods.
To do this the most generic way, I just pass down the table columns all the way (in case we need something else from it in the future).
Fixes #86.

Fixed JSON column with binlog streamer

---

utils.go

We are currently using MariaDB on production and `Executed_Gtid_Set` column is not returning for `SHOW MASTER STATUS` query
This is causing `sql: expected 4 destination arguments in Scan, not 5 ` when ghostferry wants t read binlog position
Here is our `SHOW MASTER STATUS` result
```
MariaDB [(none)]> SHOW MASTER STATUS;
+--------------------+----------+--------------+------------------+
| File               | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+--------------------+----------+--------------+------------------+
| mariadb-bin.000006 | 39818670 |              |                  |
+--------------------+----------+--------------+------------------+
1 row in set (0.00 sec)
```

Scan SHOW MASTER STATUS row depending on column count #92

---

compression_verifier.go
config.go
copydb/config.go
copydb/copydb.go
copydb/test/copydb_test.go
data_iterator.go
ferry.go
iterative_verifier.go
sharding/config.go
sharding/sharding.go
sharding/test/compression_verifier_test.go
test/go/data_iterator_test.go
test/helpers/ghostferry_helper.rb
test/integration/iterative_verifier_test.rb
test/lib/go/integrationferry.go
test/test_helper.rb
testhelpers/integration_test_case.go
verifier.go

What is done 
----------
This PR moves the initialization and management of IterativeVerifier from the application level to the core library. This is required to interrupt and resume the IterativeVerifier as otherwise the application
layer will have to assume the responsibility of resuming the IterativeVerifier correctly, which is a non-trivial task.
This also removes the `.Tables` member on the DataIterator and made it an argument of `.Run`.
Also added tests in the ruby integration tests for the IterativeVerifier.
Implication for configurations
------------------------------
Since the verifiers will be initialized by the Ferry using configurations specified in Config. The Config interface is almost the same as the previous config, so a small change for sharding is needed:
Before for …

Moved the ownership of IterativeVerifier from sharding/copydb to Ferry

---

ferry.go
iterative_verifier.go
sharding/test/trivial_integration_test.go
sharding/testhelpers/unit_test_suite.go
test/go/iterative_verifier_integration_test.go
test/go/race_conditions_integration_test.go
test/go/trivial_integration_test.go
test/go/types_integration_test.go
testhelpers/integration_test_case.go
verifier.go

We want to do this because having the TableSchemaCache be first loaded in Ferry.Start means we have to then set the instance variables of BinlogStreamer and the verifiers after it is loaded. This effectively means the initializing of the BinlogStreamer and verifiers are split between Initialize and Start, an ugly situation.
This is a surprisingly complicated task, as there is a dependency within the tests: 
1. The tests uses Ferry.SourceDB to seed the database.
2. Ferry.SourceDB is created in Ferry.Initialize()
3. Once f.Tables is populated during Ferry.Initialize(), it means all the tests will see an empty table schema cache.
4. Seeing an empty table schema cache will cause failures.
Instead, what we have to do is to create separate sql.DB instances for the tests to connect to the source …

Moved TableSchemaCache loading from Ferry.Start to Ferry.Initialize

---

config.go
copydb/cmd/main.go
copydb/copydb.go
error_handler.go
examples/copydb/conf.json
ferry.go
sharding/test/callbacks_test.go
test/lib/go/integrationferry.go

A couple of minor things done in this PR:
- Added StateDump to the Error HTTP callback so it can be posted during the ghostferry-sharding usage.
- Changed the flag DumpStateToStdoutOnSignal to DumpStateOnSignal to reflect the fact that we dump the state to not just stdout but also via HTTP.
- Added the ability to pass in a state file to CopyDB.
- Also for CopyDB: Fix the SIGTERM/SIGINT going no where when Ferry.Run finishes but the control server is still up.
I'm doing the CopyDB changes because there's a big chance that we might need to use interrupt/resume with copydb in the next couple of weeks.

Hook up interrupt/resume to copydb and sharding

---

docs/source/copydbinprod.rst
docs/source/copydbinterruptresume.rst
docs/source/index.rst
docs/source/tutorialcopydb.rst

Added some brief documentations on how to use interrupt and resume.
The website won't be updated until I merge it into master. I tried to build it for my fork, but Github pages builds are currently degraded due to some incident on their end. When it's back up, a preview of the docs can be seen at https://shuhaowu.github.io/ghostferry/interrupt-resume-docs/index.html

Updated public documentations on interrupt & resume

---

sharding/config.go
sharding/sharding.go
sharding/test/callbacks_test.go

First step of https://github.com/Shopify/ghostferry/issues/101. 
With this change, the ShardingFerry will now attempt to retry acquiring the cutover lock a configurable number of times while also waiting a configurable number of seconds between each attempt. Later, we can add a "retry-after" header or similar to tell the ferry to wait a dynamic period of time.

Retry acquisition of cutover lock on error

---

ferry.go

`user` is a pretty ambiguous ErrorHandler `from` tag. Changed to `user_interrupt` to make it more explicit, allowing us to more easily distinguish which Ghostferry run has been interrupted.

Made interrupt more explicit in ErrorHandler

---

error_handler.go
testhelpers/error_handler.go

If multiple Fatal calls to the ErrorHandler is received from multiple goroutines, the current implementation will only dump the state once using an atomic integer.  Subsequent calls will not dump the state anymore. After dumping the state, panic is called, ending the process.
However, since at some point in the past, the method Fatal was refactored such that it first calls ReportError, which dumps the states, then it panics. However, the atomic integer checking logic is within ReportError. This means, if there are multiple racing goroutines calling .Fatal, there is a chance that the state dump is either incomplete or non-existent.
This PR fixes this issue by restoring the behaviour prior to the Fatal method split by returning a boolean from ReportError, letting Fatal know if it should …

Fix state dump not showing due to concurrent Fatal

---

ferry.go
test/integration/interrupt_resume_test.rb

If LastKnownSchemaCache is nil, Ghostferry resumes by first loading the tables on the source database.
This is useful if one doesn't want to save the LastKnownSchemaCache, which could be many megabytes of data.

Resume Ghostferry without LastKnownSchemaCache

---

error_handler.go
testhelpers/error_handler.go

Follow up to #106: moved atomic check from `ReportError` to `Fatal` to avoid returning a boolean on `ReportError`.

Moved error handler atomic check to Fatal

---

error_handler.go
ferry.go
sharding/sharding.go

Since the state dump can be very noisy due to large schema caches, this commit adds an option to not dump it into stdout. This should help with any downstream logging system being clogged up by the dump into stdout.
The default has been changed such that:
- Ghostferry library: will dump to stdout if ErrorHandler is not specified
- Ghostferry-copydb: will dump to stdout
- Ghostferry-sharding: will NOT dump to stdout
Note: PanicErrorHandler.ErrorCallback will always receive the state and this remains unchanged.

Optional state dumping to stdout

---

batch_writer.go
binlog_writer.go
copydb/filter.go
copydb/test/filter_test.go
cursor.go
data_iterator.go
dml_events.go
ferry.go
filter.go
iterative_verifier.go
row_batch.go
sharding/filter.go
sharding/sharding.go
sharding/test/copy_filter_test.go
sharding/test/table_filter_test.go
table_schema_cache.go
test/go/data_iterator_test.go
test/go/dml_events_test.go
test/go/iterative_verifier_test.go
test/go/row_batch_test.go
test/go/table_schema_cache_test.go
test/go/verifier_test.go
testhelpers/test_table_filter.go
verifier.go

Instead of relying on a third party struct for such a crucial piece of information, we use an extended version of this struct so we can store custom information on it. The main purpose is to store which columns are compressed to help with implementing the InlineVerifier.
DMLEvents and RowBatch also no longer hold their own copy of the table schema structure. They originally held their own copy as we thought about dealing with schema changes dynamically. Since our present plan is to pause when a schema change occurs and resume later, we don't need this anymore. This simplifies the code as all schema structures comes from the TableSchemaCache.
Lastly, RowBatch.AsSQLQuery and DMLEvent.AsSQLString have been changed such that they take the schema and table name as string arguments instead of …

Use a custom TableSchema struct

---

config.go
control_server.go
data_iterator.go
ferry.go
http_callback.go
iterative_verifier.go
progress.go
status_deprecated.go
table_schema_cache.go
test/helpers/db_helper.rb
test/helpers/ghostferry_helper.rb
test/integration/callbacks_test.rb
test/lib/go/integrationferry.go

This PR allows progress to be reported to an HTTP endpoint periodically so an Ghostferry management software can display more detailed information about a move.
The data looks like this:
```
{
"CurrentState"=>"done", 
"CustomPayload"=>"", 
"Tables"=>{
"gftest.test_table_1"=>{"LastSuccessfulPK"=>1111, "TargetPK"=>1111, "CurrentAction"=>"completed"}
}, 
"LastSuccessfulBinlogPos"=>{"Name"=>"mysql-bin.000005", "Pos"=>31730235}, 
"BinlogStreamerLag"=>0.100753822, 
"Throttled"=>false,
"VerifierType"=>"", 
"FinalBinlogPos"=>{"Name"=>"mysql-bin.000005", "Pos"=>31730235},
"PKsPerSecond"=>9400,
"ETA"=>0, 
"TimeTaken"=>0.996557813
}
```
This PR does not have detailed progress reporting for the IterativeVerifier (no detailed table information). The `CurrentState` field will be changed to …

Report Ghostferry internal progress to a HTTP endpoint

---

test/integration/types_test.rb
test/test_helper.rb

We never explicitly tested moving escaped data, which is only ' with NO_BACKSLASH_ESCAPE.
This adds an integration test specifically for this.

Test copying escaped data

---

Makefile
batch_writer.go
config.go
copydb/test/copydb_test.go
copydb/test/filter_test.go
cursor.go
data_iterator.go
ferry.go
inline_verifier.go
row_batch.go
sharding/sharding.go
sharding/test/table_filter_test.go
table_schema_cache.go
test/go/binlog_streamer_test.go
test/go/data_iterator_test.go
test/go/iterative_verifier_test.go
test/go/table_schema_cache_test.go
test/helpers/ghostferry_helper.rb
test/integration/inline_verifier_test.rb
test/integration/iterative_verifier_test.rb
test/lib/go/integrationferry.go
test/test_helper.rb
utils.go

This PR adds verification inline while selecting data in DataIterator (Cursor) and writing data in BatchWriter. It does not add the verification to the BinlogStreamer so the PR is a reasonable size. That will come next. 
Some more notes on the InlineVerifier topic is available in #99. The tl;dr of it is:
1. Making the IterativeVerifier interruptible will significantly complicate the code base.
2. The InlineVerifier will allow us to get interrupt/resume for almost free.
3. The only type of corruption that both the IterativeVerifier and the InlineVerifier can guarantee detection is corruption due to an encoding-type bug.
4. The IterativeVerifier have can detect some additional types of corruption  (such as implementation bugs in interrupt/resume like an incorrect restart location). However, …

InlineVerifier for DataIterator/BatchWriter

---

batch_writer.go
binlog_writer.go
data_iterator.go
ferry.go
sharding/test/callbacks_test.go
state_tracker.go
status_deprecated.go
test/go/data_iterator_test.go
test/integration/interrupt_resume_test.rb
test/test_helper.rb

The `StateTracker` code was complex as it was split between the `CopyStateTracker` and the `VerifierStateTracker`. Since we are moving towards the `InlineVerifier`, which requires very little state, we don't need this complexity anymore. 
This PR removes the extra complexity and only retains a single `StateTracker` and `SerializableState`.

Removed StateTracker complexity

---

config.go
ferry.go
inline_verifier.go
test/go/table_schema_cache_test.go
test/integration/inline_verifier_test.rb
test/lib/go/integrationferry.go

The InlineVerifier doesn't verify the Binlog copied. This PR adds a reverifier component to the InlineVerifier. It periodically attempts to verify the BinlogEvents copied prior to cutover (within `PeriodicallyVerifyBinlogEvents`). If a row doesn't match, it will be added back to the queue to be verified again in the future. This process will be stopped after the DataIterator finishes copying all rows. After it is stopped, `VerifyBeforeCutover` starts. Within this phase, the verifier attempts to iterate over the verification queue until it is small enough (< 1000 binlog events by default). A maximum of 30 iterations (by default). After this is done, VerifyDuringCutover should be called by the application. During this, the verifier will return the mismatches if they are found. 
The code …

InlineVerifier Binlog Reverifier

---

batch_writer.go
ferry.go
inline_verifier.go
sharding/sharding.go
sharding/test/primary_key_table_test.go
state_tracker.go
status_deprecated.go
test/go/data_iterator_test.go
test/go/inline_verifier_test.go
test/helpers/ghostferry_helper.rb
test/integration/inline_verifier_test.rb
test/integration/interrupt_resume_test.rb

This PR makes all of Ghostferry interrupt/resumable when running with the InlineVerifier. Most of the code are the ruby integration tests.
Also note: Previously, `RunStandaloneCopy` was recording improper LastSuccessfulPK position as the BatchWriter from Ferry is reused in it. This is fixed. Furthermore, the IterativeVerifier is removed from `deltaCopyJoinedTables` and `copyPrimaryKeyTables`. Instead, RunStandaloneCopy now automatically verifies the data via the InlineVerifier.

Made InlineVerifier resumable

---

Makefile

This was causing issues for our developers running `make sharding`.
Let's ignore the LDFLAGS that are already set in the environment for a more deterministic build

Ignore LDFLAGS from environment

---

batch_writer.go
data_iterator.go

Note: I need this for some downstream tests so I can more reliably interrupt Ghostferry based on logging outputs. That said, this is probably nice in case someone wants to run Ghostferry without `-verbose`.
If debug level logs are turned off (as in ghostferry-sharding), there are no visibility of the DataIterator's progress in the logs. This PR adds at most 50 lines of logs while the DataIterator runs.
The log lines are emitted after a table is queued. Since the queue is an unbuffered channel and consumed by the tableIterators, logging here will reliably report the approximate number of tables copied by Ghostferry.

Additional info logs in DataIterator

---

cursor.go
test/integration/trivial_test.rb

Cursor emitted logs that includes the entire query. With the InlineVerifier, this query could be huge and thus clutters up the log. This change omits the columns selected, which reduces this clutter.
Example log line before this change:
```
{
"args":[923],
"level":"debug",
"msg":"found 178 rows",
"sql":"SELECT *, MD5(CONCAT(MD5(COALESCE(`id`, 'NULL')),MD5(COALESCE(`data`, 'NULL')))) AS __ghostferry_row_md5 FROM `gftest`.`test_table_1` WHERE `id` \u003e ? ORDER BY `id` LIMIT 200 FOR UPDATE",
"table":"gftest.test_table_1",
"tag":"cursor",
"time":"2019-09-25T14:11:35-04:00"
}
```
Example after:
```
{
"args":[911],
"level":"debug",
"msg":"found 187 rows",
"sql":"SELECT [omitted] FROM  `gftest`.`test_table_1` WHERE `id` \u003e ? ORDER BY `id` LIMIT 200 FOR UPDATE", …
```

Less noisy logs from the MD5 transform

---

config.go
copydb/test/copydb_test.go
copydb/test/filter_test.go
ferry.go
inline_verifier.go
sharding/sharding.go
table_schema_cache.go
test/go/binlog_streamer_test.go
test/go/data_iterator_test.go
test/go/iterative_verifier_test.go
test/go/table_schema_cache_test.go
test/helpers/ghostferry_helper.rb
test/integration/inline_verifier_test.rb
test/lib/go/integrationferry.go

This code is used in the same special case that handles the CompressedColumns: if data on the source and target already agrees with each other except for a non-critical field (say the a last_updated timestamp that does not affect the actual data integrity), the InlineVerifier should be able to be skip that particular column during verification to avoid a failed run. This option previously existed within the IterativeVerifier but I neglected to bring it over to the InlineVerifier. 
I must admit, I don't quite like how the code is structured (w.r.t. adding yet another parameter to `TableSchema` and another argument to `LoadTables()`). However, I can't see any other simple ways to get this to work. If there's some sort of cleanup/refactor we can do here, I'm all ears.

Ignore certain columns during InlineVerification

---

table_schema_cache.go
test/go/table_schema_cache_test.go
test/integration/inline_verifier_test.rb

Is a decently straightforward PR, although I do fix an issue with `NULL` vs `'NULL'`.
- Tested that InlineVerifier works across multiple charsets and collations.
- Tested positive and negative zero floating point values.
- Tested NULL values.
One thing I uncovered is that `NULL` is being treated the same as `'NULL'` by the InlineVerifier. Thus, we're prone to [false](https://www.wired.com/2015/11/null/) [negatives](https://www.wired.com/story/null-license-plate-landed-one-hacker-ticket-hell/) involving NULL. The cause of the issue is as folllows:
- To generate a checksum, for each row, we compute the MD5 of each column and concatenate the result. Then we generate yet another MD5 for this concatenated string.
- MD5 checksum is computed on the mysql server, using the `MD5` function. …

Further tests for the InlineVerifier

---

batch_writer.go
compression_verifier.go
config.go
cursor.go
data_iterator.go
dml_events.go
docs/source/copydbinterruptresume.rst
ferry.go
inline_verifier.go
iterative_verifier.go
progress.go
row_batch.go
sharding/filter.go
sharding/sharding.go
sharding/test/copy_filter_test.go
sharding/test/primary_key_table_test.go
state_tracker.go
status_deprecated.go
table_schema_cache.go
test/go/iterative_verifier_integration_test.go
test/go/iterative_verifier_test.go
test/go/race_conditions_integration_test.go
test/go/row_batch_test.go
test/go/table_schema_cache_test.go
test/go/trivial_integration_test.go
test/integration/callbacks_test.rb
test/integration/inline_verifier_test.rb
test/integration/interrupt_resume_test.rb
test/test_helper.rb
webui/index.html

Implementation of https://github.com/Shopify/ghostferry/pull/138 was a quick hack to attain the required functionality. This PR serves the sole purpose of ensuring naming now reflects the usage of `Pagination Column` as the pivot for iteration during a `Ghostferry` migration. 
In order to sift the correct usage of PK as in Primary Key vs that of Pagination Key throughout the code base, I resorted to introducing changes incrementally, commit per commit that can assist in the case a systematic mistake was made in the conversion. 
First my primary focus was to get rid off the deceptive naming off: `GetPKColumn` and to remove the unneeded index:
* Change naming GetPKColumn -> GetPaginationColumn"
* Remove unneeded index
After that, my primary focus was to convert:
* PrimaryKey -> …

Update semantics to reflect usage of Pagination Column vs PK column

---

config.go
table_schema_cache.go
test/go/table_schema_cache_test.go

_It's been a long time since I've written Go, so feel free to point out any non-idiomatic things!_
As a follow-up to https://github.com/Shopify/ghostferry/pull/138, we should use `CascadingPaginationColumnConfig.FallbackColumn` as a last resort before erroring. The current `master` will use the fallback column before attempting to use the primary key.
```ruby
CascadingPaginationColumnConfig: {
PerTable: {
'my_db_schema' => {
products: 'id',
},
},
FallbackColumn: 'id'
}
```
https://github.com/Shopify/ghostferry/blob/7d01d7044d4b8577462657a8bf625a52453be7e9/table_schema_cache.go#L241-L253
We will still error if the PK or `FallbackColumn` is non-numeric. I'm not sure if we should use the `FallbackColumn` if the PK is non-numeric, but for now we only check numericality after all of the above …

Use CascadingPaginationColumnConfig.FallbackColumn as fallback after Primary Key

---

cursor.go
dml_events.go
inline_verifier.go
table_schema_cache.go
test/integration/inline_verifier_test.rb

The current InlineVerifier code uses `.PKColumns[0]` to identify the pagination column in the binlog verification. This causes **false negatives** in the verification for tables with certain composite PK tables.
This PR fixes this issue and adds the appropriate tests.

InlineVerifier is not validating some tables with composite PKs correctly

---

dml_events.go
test/integration/types_test.rb

A DELETE or UPDATE statement issued by the BinlogWriter on a table with a JSON column could result in the row not being deleted or updated, which causes data corruption. The InlineVerifier and IterativeVerifier will catch this corruption during cutover(1).
Before this PR, the query generated by the BinlogWriter for JSON tables looks like:
```
INSERT IGNORE INTO `gftest`.`test_table_1` (`id`,`data`) 
VALUES (2,'{}');
UPDATE `gftest`.`test_table_1` 
SET `id`=2,`data`='["test_data","test_data_2"]'
WHERE `id`=2 AND `data`='{}';
DELETE FROM `gftest`.`test_table_1` 
WHERE `id`=3 AND `data`='["test_data","test_data_2"]';
```
After:
```
INSERT IGNORE INTO `gftest`.`test_table_1` (`id`,`data`) 
VALUES (2,CAST('{}' AS JSON));
UPDATE `gftest`.`test_table_1` 
SET …
```

Fix possible data corruption due to UPDATE/DELETE not applied on tables with JSON columns

---

inline_verifier.go

Right now, any table/schemas that are checked are emitted in the mismatches hash, even if there are not mismatches. Thus, you get mismatch messages that looks like:
```
cutover verification failed for:
database.table1 [pks: 1 2 3 ]
database.table2 [pks: ]
```
In this example, only database.table1 have mismatches, but table2 is emitted. This commit fixes it such that only database.table1 is emitted.

Makes discrepency error less noisy

---

ferry.go
test/go/state_tracker_test.go
test/integration/interrupt_resume_test.rb
test/test_helper.rb

If the VerifierType is not Inline, there's no point in recording the InlineVerifier binlog position in the state dump. This is done right now because the code records the binlog position at the beginning of a run. This actually somewhat misleading as it makes people using Ghostferry without verification might think the InlineVerifier is running due to its presence in the state dump.

Do not record InlineVerifier pos in state dump if not verifying

---

dml_events.go
test/integration/types_test.rb

The bug this attempts to workaround is here: https://bugs.mysql.com/bug.php?id=98496
This effectively implements the suggested fix as above.. except this occurs during binlog copying from source to target. During the data copy process, we've already coerced `''` into `'null'` as mysql server returns `'null'` when it sees `''` internally.
Other related bugs:
- https://github.com/siddontang/go-mysql/issues/267 
- https://github.com/siddontang/go-mysql/issues/266

Fixing panic encountered in BinlogWriter when operations are performed on the tables with JSON NOT NULL columns

---

.gitignore
config.go
sqlwrapper/ghostferry_db.go
test/go/binlog_streamer_test.go
test/go/iterative_verifier_collation_test.go
test/go/race_conditions_integration_test.go
testhelpers/test_ferry.go

Need to differentiate Technical Ghostferry's binlog events from Core's Business binlog events
Add `/*maintenance:ghostferry*/` comment to all change queries that are executed by Ghostferry.

Add maintenance comment to all sql change queries

---

copydb/config.go
copydb/copydb.go
copydb/test/copydb_test.go
table_schema_cache.go
test/go/table_schema_cache_test.go

This commit introduces the ability for ghostferry-copydb to create
tables in a specific order. This can be useful if tables to be created
contain foreign-key constraints (FKCs).
NOTE: This does not mean that ghostferry supports FKCs! However, with
this feature and by disabling FKCs in the target DB, it is
theoretically possible to migrate DBs with FKCs - this is experimental
and not recommended for production usage. Use with care!
To disable the FKCs, one must add the following config to the target DB
configuration:
"Params": {
"foreign_key_checks": "0"
}

Allow specifying table creation order #161

---

.travis.yml
binlog_streamer.go
binlog_writer.go
dml_events.go
ferry.go
inline_verifier.go
sharding/test/copy_filter_test.go
state_tracker.go
test/go/dml_events_test.go
test/integration/interrupt_resume_test.rb
test/integration/trivial_test.rb
test/lib/go/integrationferry.go
test/test_helper.rb
testhelpers/unit_test_suite.go

Alternative to https://github.com/Shopify/ghostferry/pull/160 (and also makes use of the same added test with slight modifications).
As described in the other PR, attempting to resume Ghostferry from an invalid binlog position will result in an error as the preceding `TableMapEvent` is required to properly translate `RowsEvents`. 
This adds a resumable position and interface to the `DMLEvent` that the `InlineVerifier` and `BinlogWriter` persist during interruption to be reused during resume. 
The last resumable position is stored as a member of the `BinlogStreamer` and is periodically updated as the `BinlogStreamer` sees new resumable events (`GTIDEvents` and `XIDEvents`). This position is then sent along with the corresponding `DMLEvent`. The resumable position is made available on the …

Fix resumable binlog position after interrupt

---

config.go
sqlwrapper/ghostferry_db.go
test/go/config_test.go
testhelpers/test_ferry.go

Follow up of https://github.com/Shopify/ghostferry/pull/155.
Sets a default marginalia value when not provided by the configuration.
Previous to this PR, if an annotation/marginalia was not provided, Ghostferry's DMLs would not have any annotation. After this change, if an annotation is not provided, Ghostferry will fallback to using the default annotation (`application:ghostferry`).
This is needed for an upcoming PR that will require use of these annotations to validate DMLs against the Target for the duration of the move (until cutover). 
/cc @Shopify/pods

add default marginalia value

---

Makefile
batch_writer.go
binlog_streamer.go
docker-compose.yml
ferry.go
status_deprecated.go
test/helpers/data_writer_helper.rb
test/helpers/db_helper.rb
test/integration/interrupt_resume_test.rb
test/test_helper.rb

Lot of small changes here:
* Reduce `max_binlog_size` in tests. This will exercise the binlog rotation codepath a lot more.
* Introduce a `currentBinlogFilename` variable and remove the implicit assumption that `lastStreamedPosition.Name` is the _current_ filename as well. This is a source of a lot of confusion.
* Consider fake events (some `RotateEvent`s and some `FormatDescriptionEvent`s) positions as invalid and don't advance our binlog position based on them
* Remove all mutations of all `mysql.Position` variables. Recreate the values from fresh state instead.
* Make the event handler `switch` statement completely imperative. Make it extra clear when `s.updateLastStreamedPosAndTime` is called.
* Fix a bug where we don't update the binlog position on `GenericEvent`s. This was causing …

Clean up binlog streamer state tracking and reduce binlog file size to test binlog rotations

---

Gemfile
Gemfile.lock
test/helpers/db_helper.rb

This almost doubles the ruby integration test performance:
on this branch:
```
Finished in 24.404618s, 0.4098 runs/s, 4.5893 assertions/s.
10 runs, 112 assertions, 0 failures, 0 errors, 0 skips
```
vs
`fast-rotations` branch:
```
Finished in 50.197126s, 0.1992 runs/s, 2.2312 assertions/s.
10 runs, 112 assertions, 0 failures, 0 errors, 0 skips
```

2x speed up in ruby integration tests

---

binlog_streamer.go
binlog_writer.go
dml_events.go
docker-compose.yml
sharding/test/copy_filter_test.go
sqlwrapper/ghostferry_db.go
test/go/dml_events_test.go
test/go/race_conditions_integration_test.go

Part of https://github.com/Shopify/ghostferry/issues/173.
Captures `RowsQueryEvent`s in the `BinlogStreamer` and passes them to the `DMLEvent`s. An added `Annotation` method is provided on the `DMLEvent` interface to expose annotations/marginalia in the `DMLEvent`s query.
This also includes a slight refactor of the `DMLEvent`s to accept a `DMLEventBase` directly instead of instantiating the struct directly inside each individual DML. 
Lastly, the `Annotate` method was moved into the `BinlogWriter` to support transactions and multiple statements as the `BinlogWriter` uses a `BEGIN; ...; COMMIT` syntax. Additional tests will be added with the follow-up PR in integration tests.
A follow up PR will be created to use these annotations to validate the `DMLEvent`s streamed from the …

Capture RowsQueryEvents; add annotations to DML events

---

ferry.go
status_deprecated.go
test/integration/interrupt_resume_test.rb

Since we are so close to being done during the cutover state, it makes sense to ignore the termination signals and complete the database replication/move.
cc @Shopify/pods

Ignore termination signals during cutover

---

copydb/config.go
copydb/copydb.go
copydb/test/copydb_test.go

This will make it configurable to allow an already existing table in target. Default will be to not allow it, just like today.
There are a few use-cases where this could make sense, for example if you want to make changes to a large table before you fill it with data (eg. new defaults, new composite primary key or new indices). Another use case is if you already have a table with data that you want to pad with data from your source database.

Allow target table to already exist in CopydbFerry

---

status_deprecated.go

Fix crash when rendering web UI introduced in Shopify/ghostferry#179.
> template: index.html:82:24: executing "index.html" at : error calling eq: incompatible types for comparison

Cast OverallState to string in StatusDeprecated

---

inline_verifier.go

We failed to check the error object after running the fingerprint query in the inline verifier.
Panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50a1ec]
goroutine 277 [running]:
database/sql.(*Rows).Columns(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/lib/go-1.10/src/database/sql/sql.go:2700 +0x3c
github.com/Shopify/ghostferry.(*InlineVerifier).getFingerprintDataFromDb(0xc4202a5c80, 0xc4201530c0, 0xc4202e6780, 0xc420028960, 0x18, 0xc4201c2130, 0xc, 0xc428eaafc0, 0xc42002dcc0, 0xc423359800, ...)
/go/src/github.com/Shopify/ghostferry/inline_verifier.go:428 +0x227
github.com/Shopify/ghostferry.(*InlineVerifier).getFingerprintDataFromTargetDb(0xc4202a5c80, 0xc420028960, 0x18, 0xc4201c2130, 0xc, …
```

Catch error from queries in getFingerprintDataFromDb

---

ferry.go
inline_verifier.go

The InlineVerifier did not implement interface needed by the ControlServer to start VerifyDuringCutover when cutover is occuring. As a result, using the InlineVerifier with copydb will result in the binlogs not verified.
This commit implements the aforementioned interface by adapting the code from the IterativeVerifier.
FYI: I'm still setting up a local test setup to test this as we don't have test coverage for this :(

Enabled InlineVerifier to work with ControlServer

---

ferry.go
inline_verifier.go
iterative_verifier.go
progress.go
status_deprecated.go
test/integration/callbacks_test.rb
verifier.go
webui/index.html

This way the InlineVerifier can report how many rows is in its reverify queue, which may help sanity check in a move. Example screen shot:
I also added this to `ReportProgress`, which means any consumer of Ghostferry's API callbacks can also use this information.

Display additional verifier info in progress

---

ferry.go

As it stands, the inline verifier periodic reverifier will be stopped the moment data copy is complete. Then, `VerifyBeforeCutover` is called which further reduces the reverification queue. After this, the reverification queue can only grow. When AutomaticCutover is set to false, the code is blocked until that variable is set to true (which occurs when a human operator hits a button in the ControlServer). This means the growth of that reverification queue is unbounded. Since the reverification is performed during the cutover, this means the verification could take an unbounded amount of time.
The above described scenario really only impacts copydb, as sharding always sets AutomaticCutover to be true and coordinates with an external service using HTTP to perform cutover. As a result, the …

Moved VerifyBeforeCutover after wait for cutover

---

Makefile

Make biting me once again. Need to set ulimit in the same shell out for this to work properly.

Actually set ulimit when running Go tests

---

.travis.yml

After switching to Travis jobs and merging to master we could see that the deploy steps that only trigger on master ran on both jobs, causing it to upload docs and packages twice. This can be solved using stages and delay the deploy to after testing. These steps are skipped on PRs.
This is what it looks like:

Use stages on Travis

---

config.go
ferry.go
test/helpers/ghostferry_helper.rb
test/integration/callbacks_test.rb
test/integration/interrupt_resume_test.rb
test/lib/go/integrationferry.go

Part of https://github.com/Shopify/ghostferry/issues/200
This PR adds a periodic callback of the run's state, very similar to how the progress callback is performed. Tests were added that both verify the callback is performed correctly and also that the state sent in the callback can be used to successfully resume an interrupted/failed move.
While we're still yet to complete formal verification of Ghostferry's idempotence with TLA+, we have verified the correctness with [integration tests](https://github.com/Shopify/ghostferry/pull/202), and have enough confidence to move forward with this PR.
[This branch](https://github.com/Shopify/ghostferry/tree/idempotence-tla-shuhao) contains the latest TLA+ proving the DataIterator's idempotence (the BinlogStreamer is next). We're targeting to wrap …

Add periodic state callback

---

config.go
copydb/copydb.go
sharding/sharding.go
test/go/config_test.go

We noticed an issue with config not being loaded and validated fully before `RunFerryFromReplica` acquire its first connection in sharding. This PR will re-apply UNIX support and delay `RunFerryFromReplica` initialization to after config is fully loaded.

Re-apply UNIX support and load config before RunFerryFromReplica

---

tlaplus/ghostferry.tla
tlaplus/ghostferry.toolbox/ghostferry___GhostferryPrimaryModel.launch

Huge thanks to @fjordan for helping me with all of these. We tackled this problem via the multiple starting state feature of TLC as follows:
Instead of interrupting and then resuming in TLA as that would be messy and difficult to check, we generate starting states for the SourceTable and TargetTable such that it looks like it was previously interrupted. This is a multiple-starting state approach that significantly increases the search space of the TLC run.
We also generate a valid "LastSuccessfulPK" that will be valid given the table states such that some of the initial states will cause the Ghostferry algorithm to re-copy previously copied rows. There's no mathematical proof that as long as we can re-copy one row correctly, we can re-copy n rows correctly, but intuition says this is …

Ghostferry interrupt resume idempotence TLA+ modifications

---

config.go
ferry.go

The schema cache can be quite big. Not emitting it may play nicer with HTTP requests max size...

Remove schema cache from state dump

---

batch_writer.go
ferry.go
inline_verifier.go
test/helpers/ghostferry_helper.rb
test/integration/inline_verifier_test.rb
test/integration/interrupt_resume_test.rb

This commit fixes a false positive problem with the InlineVerifier, which is documented in #149. That bug report documented a relatively complex and uncommon race condition that could occur and result in a false positive inline verifier error. However, with the presence of interrupt resume with periodic snapshots in the past, this problem becomes a lot more prevalent. An example case is given in the test, and is also given below for reference:
| Step | Action             | Source | Target | Notes |
|------|--------------------|--------|--------|-------|
| 0    | Initial State      | v1     | nil    |       |
| 1    | State Dump         | v1     | nil    |       |
| 2    | Copy row           | v1     | v1     |       |
| 3    | Interrupt          | v1     | v1     |       |
| 4    | App …

False positive InlineVerifier errors

---

config.go

We have had a couple of 4 hour slow queries during a migration. These could have been more easily found if the MySQL client in Ghostferry would have timed out faster and retried or crashed after 4 retries if persistent. I've set the time to 30 seconds for both reads and writes here, maybe we want this configurable, but also don't feel for adding more complexity to config.
Ps. Using a very large chunk size might mean it takes more than 30 seconds, this case isn't really cared for in this PR. We could increase the time to 60s or so, everything is better than 4 hours here.
**Update:** I've made it configurable and set fallback to 60s.

Make MySQL read and write timeout configurable

---

binlog_streamer.go

I have strong suspicion that the `WithRetries` for `binlogStreamer.GetEvent` (siddontang library call) in `BinlogStreamer.Run` (ghostferry code) is not needed. If we look at the `binlogStreamer.GetEvent` code, it is:
```
// GetEvent gets the binlog event one by one, it will block until Syncer receives any events from MySQL
// or meets a sync error. You can pass a context (like Cancel or Timeout) to break the block.
func (s *BinlogStreamer) GetEvent(ctx context.Context) (*BinlogEvent, error) {
if s.err != nil {
return nil, ErrNeedSyncAgain
}
select {
case c := <-s.ch:
return c, nil
case s.err = <-s.ech:
return nil, s.err
case <-ctx.Done():
return nil, ctx.Err()
}
}
```
There are two possible error cases: (1) when `ctx.Done()` is true, and (2) when `s.ech` receives an error. In the first …

Log binlog streamer error for now

---

config.go
copydb/test/copydb_test.go
copydb/test/filter_test.go
examples/copydb/conf.json
ferry.go
sharding/sharding.go
table_schema_cache.go
test/go/binlog_streamer_test.go
test/go/data_iterator_test.go
test/go/iterative_verifier_test.go
test/go/table_schema_cache_test.go

Sometime you might run in to a mad query plan during copy, this new option will help to force an index during inline verification.
Example config:
```json
"ForceIndexForVerification": {
"gftest": {
"table1": "forced_index_name"
}
}
```

Allow index forcing in inline verifier

---

docs/source/copydbinprod.rst
docs/source/copydbinterruptresume.rst
docs/source/technicaloverview.rst
docs/source/tutorialcopydb.rst
docs/source/verifiers.rst

I was going through the (awesome) documentation and noticed some typos and a few inconsistencies.
This is a small PR to address some of those.
It appears the ~`TargetVerifier`~ `IterativeVerifier` is deprecated, and not referenced within the main section of `Verifiers`. I've updated that part of the documentation to state there are two verifiers currently supported.

Edit Documentation

---

README.md
dev.yml

For internal contributors, let's assert `docker-compose` is present in the `dev up` pipeline. On my machine, `Docker.app` was present but `Docker`, and its related tooling, wasn't yet installed. 
Let's strengthen the `met?` condition by asserting `which docker-compose` returns a non-error status code.
I also made some small additions to the README.

Assert presence of docker-compose on dev up

---

inline_verifier.go
test/integration/callbacks_test.rb

The currentRowCount emitted before can count the same row multiple times, which does not allow for a great estimate of how big the state dump could be. With this patch, we emit both the row count (which is maybe useful to estimate how long it would take to reverify) and the entries count (which is useful to estimate how big the statedump is) in the VerifierMessage that's dumped to the progress, which will allow us to estimate the size of the state dump.
Fixes #234

Added binlog verify store entry count

---

.travis.yml

Build debian packages for the experimental branch, so we can test some more experimental changes in downstream consumers.

Experimental branch also builds debian packages

---

ferry.go
test/integration/callbacks_test.rb

Closes #232
This PR helps ensure progress is reported before beginning cutover.
Ghostferry, as a library, can't enforce or ensure that clients don't terminate/error-out during cutover. Custom code leaves this as a possibility.
Before notifying clients that row copy is complete, we should dispatch a progress callback. 
This conditional change comes before the notification (`notifyRowCopyCompletion`), to avoid any possible race conditions. If the notification of row completion occurs first, the client (ex: `copydb`, `sharding`) could execute, and possibly fail, before the progress callback is emitted.
---
I've add an integration test for this specific use case. Namely, simulate a Ghostferry client that is killed after row copy complete has finished.
Assertions are put in place to now make …

Report progress before cutover begins

---

docs/source/copydbinprod.rst

`zero downtime` is considered a common term and is more readable than `0 downtime`.

[Docs] “zero downtime” instead of "0 downtime"

---

test/test_helper.rb

We prescribe using two MySQL instances in the [follow-along docs/tutorial](https://github.com/Shopify/ghostferry/blob/master/docs/source/tutorialcopydb.rst). We also use the same database instances for [running the test suite.](https://github.com/Shopify/ghostferry/blob/master/test/helpers/db_helper.rb#L6)
This left me in an interesting state. After running the test suite, and then later following along with the tutorial, my databases were pre-seeded.
This PR ensures that we clear test state after each the suite completes. I don't have particularly strong feelings on doing this, so I'm open to hear reasons against dropping state before and after every _test suite run_ (note: not every _test_ run). 
This PR also calls super in the `before_*` and `after_*` setup/teardown methods as …

Reset database state after test suite runs

---

ferry.go

We currently don't log anything when resuming from state. This PR will add a log line and the MySQL positions. I'm not logging out any table positions nor schemas since this data might be very large at times.
~~Also found a state tracker init from state bug.~~
Edit: Moved the state tracker bug to a separate PR since it seems to be a bigger issue.

Log when resuming from state

---

state_tracker.go

When resuming from a state dump we accidentally initiated the state tracker's `lastStoredBinlogPositionForTargetVerifier` with the inline verifiers binlog position. This means that until an event is received on the target binlog streamer, we will report a corrupted state. Once an event is received, the value will auto-correct.

Set lastStoredBinlogPositionForTargetVerifier correctly on resume

---

config.go
cursor.go
ferry.go
progress.go
test/go/data_iterator_test.go

This PR adds the ability to dynamically calculate the batch size using linear interpolation for all tables
Added a new `DataIterationBatchSizePerTableOverride` struct to the config 
For example, we can pass this into the config
```
{
MinAvgRowLength: 200
MaxAvgRowLength: 10000
ControlPoints: {
200:  5000,
10000: 200,
3000:  4000,
4000:  3500,
5000:  3000,
}
}
Optionally, we can also pass in a set batch size for a given table if we don't want to calculate it for that specific table
{
MinAvgRowLength: 200
MaxAvgRowLength: 10000
ControlPoints: {
200:  5000,
10000: 200,
3000:  4000,
4000:  3500,
5000:  3000,
}
TableOverride : {
"SchemaA": {
"TableA": 200
}
}
}
```
For a table with `avg_row_length` of 3500, we would use the data points `3000` and `4000` to evaluate the batch size of `3750` …

Dynamically calculate batch size per table

---

binlog_streamer.go
ferry.go
table_schema_cache.go
test/go/binlog_streamer_test.go
test/go/table_schema_cache_test.go
testhelpers/data_writer.go

Fixes an issue in the `TargetVerifier` if there happened to be any configured schema or table rewrites.
This patch correctly handles any configured rewrites by reversing the configurations to lookup DML events using the Source `TableSchemaCache` from DML events streamed on the Target. 
Note that If there are duplicate values in the original rewrites, an error will be raised and Target Verification will not be able to be used as Ghostferry will not be able to correctly map the DML back to the Source.
Previous to this fix,  if running Ghostferry with schema or table rewrites, it would fail to inspect binlog events on the Target, and, as a result, fail to update its position in the `StateTracker`.
As you can see in the snippet below, the `BinlogStreamer` in the `TargetVerifier` would …

Fix BinlogStreamer for TargetVerifier by correctly handling rewrites

---

control_server.go

Incorrectly setting the `TargetPaginationKey` in the `ControlServerStatus`. Also ordered the tables, grouping them in `completed, copying, waiting` so it doesn't change order all the time. 
Before: 
After:

Fix TargetPaginationKey in controlserver status

---

config.go
copydb/config.go
ferry.go
test/go/ferry_test.go

Closes #3 
Ghostferry doesn't support copying tables with Foreign Key constraints. Currently, we let the Ghostferry run begin to eventually crash midway through the run.
We should enforce this decision by erroring out during initialization, instead.
This PR queries the `information_schemas` to determine if any `FOREIGN KEY` constraints exist on any of the tables that will be copied by the Ghostferry (namely those after filtering / that are applicable).
Clients of Ghostferry may want to skip the enforcement, therefore, we leave it as a configurable option.
One instance, for example, is #166. That PR allows the ability to configure a specific ordering on tables, intended to be used to circumvent FOREIGN KEY issues. In the case when `TablesToBeCreatedFirst ` is non-zero, the …

Enforce foreign key constraints are not present during initialization

---

binlog_streamer.go
dml_events.go

Over the last little while we introduced some memory leaks while resolving other issues. Two problems include:
1. a slice-to-string conversion in `DMLEventBase.Annotation`, from now on referred to as the `string leak`. This leak only occurs when the target verifier is on.
2. a case where we called deferred in a loop, from now on referred to as the `defer leak`. This leak occurs whenever the binlog streamer runs (so in all normal ghostferry configurations).
A benchmark run was conducted with our internal setup and showed the following Ghostferry RSS usage before and after the fix.
We originally thought that we were impacted by [this Golang issue](https://github.com/golang/go/issues/42330), so all tests in the above plot (except the green line) is conducted with MADV_DONTNEED. It turns out …

Fixed two newly introduced memory leaks

---

batch_writer.go
config.go
cursor.go
ferry.go
progress.go
row_batch.go
state_tracker.go
test/go/row_batch_test.go
test/integration/callbacks_test.rb
test/lib/go/integrationferry.go

Related: https://github.com/Shopify/ghostferry/issues/226 
Similar PR: https://github.com/Shopify/ghostferry/pull/228 
Add an estimate of number of bytes for each row batch and sending it with the `progress` callback

Add estimated row batch size in bytes to state

---

sharding/metrics.go

I'm seeing metrics sink full warnings in production spamming our logs. I tested making the buffer bigger and it appears to have helped...
That said, I'm not sure why making metrics buffer bigger actually solves the problem, because there's should be a "conservation of mass" type dynamics: the number of metrics going into the channel should equal the number coming out for the channel to not be filled. I guess buffers for audio workstations also have similar behaviours, so maybe I should just read up more about how buffers work.

sharding: made metrics buffer bigger

---

config.go
copydb/cmd/main.go
copydb/copydb.go
ferry.go
sharding/config.go
sharding/sharding.go
sharding/test/callbacks_test.go
sharding/testhelpers/unit_test_suite.go

Refactoring the code so the shared config between copydb and sharding allow `CutoverLock` and `CutoverUnlock` callbacks.

Enable Cutover callback in config for copydb

---

binlog_writer.go
config.go
data_iterator.go
data_iterator_sorter.go
dml_events.go
ferry.go
progress.go
row_batch.go
sharding/test/copy_filter_test.go
test/go/dml_events_test.go

The binlog writer and binlog streamer lag can diverge. This allows us to track them individually in the Progress struct. 
Furthermore, the target binlog streamer lag is a thing when the TargetVerifier is active, this allows us to track that lag when it is in use.
Also ran go fmt in a few places. We should probably setup CI to catch format issues.

Binlog writer lag and target binlog streamer lag 

---

ferry.go

During our recent test run, we noticed that the Target Binlog Streamer can be significantly lagged during cutover when the Target Verification is enabled. This caused longer than necessary downtime during cutover. This PR addresses the issue by waiting for Target Binlog Streamer to catch up before entering cutover, like how we currently wait for the Source Binlog Streamer.

Add wait for Target Binlog Streamer to catch up before cutover

---

Makefile

With the comment after the DATETIME variable in make, the extra space before the `#` symbol was interpreted as a part of the variable...

Fixed make file

---

copydb/cmd/main.go

During the initial setup for the `ferry` in copydb we were not reporting errors to error callback. Before the ferry runs we are doing a bunch of initialization work which is prone to fail but we were simply exiting from copydb and not reporting these errors to error callback-server. This PR fixes that.

report error to the callback if ferry initialization fails in copydb

---

config.go
ferry.go
test/go/ferry_test.go

Add `AllowSuperUserOnReadOnly` so that ghostferry user can write to the target DB even if it is read_only.

add AllowSuperUserOnReadOnly flag

---

copydb/copydb.go
copydb/test/copydb_test.go

Copydb, when creating the database, didn't preserve the database collation setting from the source side. This fixes it.

Preserve collation in create database for copydb

---

config.go
control_server.go
copydb/cmd/main.go
copydb/copydb.go
copydb/test/copydb_test.go
cursor.go
examples/copydb/conf.json
ferry.go
iterative_verifier.go
test/go/config_test.go
test/go/data_iterator_test.go
test/go/iterative_verifier_integration_test.go
test/go/iterative_verifier_test.go
test/go/race_conditions_integration_test.go
webui/index.html

Re: https://github.com/Shopify/ghostferry/issues/265
As part of the above issue I was looking into a way to implement dynamic configuration via the control server.
This PR adds a new endpoint to the `ControlServer` which allows dynamic reconfiguration, currently it only supports updating the `DataIterationBatchSize` value.
Another important change is the move of  `ControlServer` into `Ferry` as an optional component, disabled by default and enabled for copydb. This will allow to use the dynamic reconfiguration and other `ControlServer` endpoints outside of copydb.

Dynamic reconfiguration for DataIterationBatchSize

---

control_server.go

This PR adds a GET `/api/config` endpot to expose updatable config, this could be used to prepopule UI input prior to update or to validate that values were updated

added a GET /api/config endpoint to expose updatable config values

---

.github/workflows/start-mysql.sh
docker-compose.yml

Specifiying the platform as x86_64 is needed for the m1 laptops,
this allows the development environment to boot up with rosetta.
I was able to run the: `make copydb && ghostferry-copydb -verbose examples/copydb/conf.json`
command with no issue. 
I suspect this should still work on a regular intel mac but I have not tested it. 
```shell
ghostferry git:(m1_compatibility) make copydb && ghostferry-copydb -verbose examples/copydb/conf.json
go build -ldflags "-X github.com/Shopify/ghostferry.VersionString=1.1.0+20211209173642+5f483a4" -o /Users/grpm/bin/ghostferry-copydb ./copydb/cmd
INFO[0000] hello world from 1.1.0+20211209173642+5f483a4  tag=ferry
INFO[0000] connecting to database                        dbname=source dsn="root:<masked>@tcp(127.0.0.1:29291)/?checkConnLiveness=false&collation …
```

Add platform to docker compose

---

Makefile

This makes the download for gotestsum work on the various `arch` cases that we require (arm64 and x86_64)
Co-authored-by: Aaron Brady <aaron.brady@shopify.com>

fix gotestsum arch checks

---

dev.yml

`dev.yml` was still using Docker and `docker-compose`. Changed it so that it uses `podman` and `podman-compose` instead.
I did run the go test and they all passed. I don't think this would change anything with the behaviour of the code itself, so it should be safe enough.

Change Docker to Podman when using dev (only for internal use)

---

.github/workflows/tests.yml
dev.yml
shell.nix

there are a few hiccups when setting up ghostferry locally, so this PR addresses these issues:
- some modules require go version 1.18
- use correct dev `mysql_client` package

update dev setup

---

.github/workflows/build-docs.sh
docs/source/conf.py
docs/source/verifiers.rst

The Sphinx update introduced just a few minor changes to the page: spacing in navbar and slightly different looks of the code blocks. I'd say we keep these defaults?
Tested the build locally using podman ubuntu

Fix docs build & warnings, update sphinx deps and create a venv to avoid clashes

---

data_iterator.go
ferry.go
test/go/data_iterator_sorter_test.go
test/go/data_iterator_test.go

We had an issue that Progress reporter would try to start using `TargetPaginationKeys`, before `Run()` function was even started in goroutine, causing 
```
panic: runtime error: invalid memory address or nil pointer dereference
```
This should fix it, by initializing `TargetPaginationKeys` early in constructor instead.

Initialize TargetPaginationKeys in constructor
