Shopify/ghostferry

- README.md
I setup a quick IRC channel so that others can talk to us. Just adding the instructions here.
> Add IRC channel to README

- README.md
- copydb/config.go
- docs/Makefile
- docs/source/conf.py
- docs/source/copydbinprod.rst
- docs/source/development.rst
- docs/source/howtousecustom.rst
- docs/source/index.rst
- docs/source/introduction.rst
- docs/source/technicaloverview.rst
- docs/source/tutorialcopydb.rst
- docs/source/verifiers.rst
Added a host of Sphinx based documentations on how to operate Ghostferry.
Preview of the current documentations: https://shopify.github.io/ghostferry
What's missing is how to use Ghostferry in a custom application. I'll do that in another time.
> Documentations

- .travis.yml
See: https://github.com/travis-ci/travis-ci/issues/7780
> Fixed deploying gh-pages on both master and tags

- .travis.yml
> Deploy to packagecloud on staging-* branches in addition to master

- sharding/config.go
- sharding/sharding.go
- sharding/test/replication_config_test.go
- sharding/testhelpers/unit_test_suite.go
Continuation of work in https://github.com/Shopify/ghostferry/pull/30
@Shopify/pods
> sharding: support running ferry off replica

- sharding/test/compression_verifier_test.go
- sharding/testhelpers/unit_test_suite.go
Add some basic integration testing for https://github.com/Shopify/ghostferry/pull/57
@Shopify/pods
> sharding: add integration testing for compression verifier

- iterative_verifier.go
fix https://github.com/Shopify/ghostferry/issues/76
> remove redundant WaitGroup done

- .gitignore
- config.go
- copydb/test/copydb_test.go
- copydb/test/filter_test.go
- ferry.go
- sharding/sharding.go
- sharding/test/copy_filter_test.go
- table_schema_cache.go
- test/go/binlog_streamer_test.go
- test/go/data_iterator_test.go
- test/go/iterative_verifier_test.go
- test/go/table_schema_cache_test.go
This addresses [Support iteration on non-PK unique integer column](https://github.com/Shopify/ghostferry/issues/96)
> Iterate by column

- test/integration/types_test.rb
Apparently valid json includes: `"null", "true", "false", "<any number>"`
This adds it into the integration test and test all statements (INSERT/UPDATE/DELETE).
However, there is apparently a case where a `"null"` value can be inserted but show up as an empty string in the binlog. See https://github.com/siddontang/go-mysql/pull/267 and https://github.com/siddontang/go-mysql/pull/266 (in Chinese). I can't reproduce this locally in the test case although a workaround should be provided by @danieloliveira079 in a separate PR.
> Added more JSON types to integration test

- config.go
- test/go/config_test.go
If you are lucky and have access to your database through a UNIX socket, it would be beneficial to use this instead of TCP. This PR will allow Source and Target to be configured to connect using UNIX or TCP.
100% backwards compatibility and will default to TCP mode.
Example config:
```
{
"Source": {
"Net": "unix",
"Host": "/tmp/mysql.sock",
"User": "root"
}
}
```
> Add support for UNIX connections

- dml_events.go
- test/go/trivial_integration_test.go
- test/integration/types_test.rb
This fixes #165.
The root cause of this problem is complex and only revealed itself from Git archeology. The comment in the code explains it the best:
For historical reasons, this function ended up being used at two different places: the DataIterator and the DMLEvent (which indirectly is used by the BinlogStreamer, InlineVerifier, etc).
The original code here was introduced in 152caec0ff5195d4698672df6dc0f72fb77b02fc, where it is used solely in context of the DataIterator. In this context, the value being parsed here is given to us by the go-sql-driver/mysql driver. This value could either by int64 or it could be a byte slice decimal string with the uint64 value in it, which is why we have this awkward byte slice to integer trick. This also means the original code is not designed to …
> Fixes panic due to Uint64 conversion in DMLEvent (RowData)

- config.go
- test/go/config_test.go
Temporarily revert UNIX support while we investigate an issue.
> Revert "Merge pull request #186 from Shopify/unix-support"

- docs/source/verifiers.rst
This transcribes an internal document we have comparing the properties of the different verifiers. The intricacies of the verifiers should probably be documented better, but this is a start.
> Compare the properties of the verifiers in a table.

- .travisci/deploy-packagecloud.sh
All is in the title. I simply need the same package pushed in for other ubuntu bases.
> Update the list of package cloud ubuntu dists

- .envrc
- gemset.nix
- shell.nix
This will help us develop on a Cloud Linux VM where `dev` is not available.
> Development with shell.nix

- binlog_streamer.go
- ferry.go
So we can differentiate the logs...
> Tagged target verifier's binlog streamer with tgt_binlog_streamer

- README.md
- ferry.go
This PR addresses this issue: https://github.com/Shopify/ghostferry/issues/251#issuecomment-776562382
I wasn't able to reproduce the issue myself but this should help in case  we somehow get there.
> Prevent ETA from becoming a negative value

- binlog_streamer.go
#260 
Using the `WithRetries` block we override the error from `s.binlogStreamer.GetEvent(ctx)` since the library returns a new error if `s.err` is set [here](https://github.com/siddontang/go-mysql/blob/master/replication/binlogstreamer.go#L26). 
We want to return the first error raised and not `ErrNeedSyncAgain`
> Remove WithRetries block to return first error

- control_server.go
- webui/index.html
Adding in a way to communicate with the API via JSON.
This is a rough draft of what the API will look like and how it will behave.
> JSON Enpoints

- config.go
- error_handler.go
- examples/copydb/conf.json
- ferry.go
- test/lib/go/integrationferry.go
Creating a configurable variable called `DumpStateToStdoutOnError` to dump state to stdout on error.
> [minor changes to config format] variable to configure dumping state to stdout on errors. 

- binlog_streamer.go
> Fix implementation of SHOW SLAVE HOSTS for different mysql versions

- table_schema_cache.go
- test/go/table_schema_cache_test.go
> Fixes mediumint not being recognized as number

- docker-compose.yml
It's been using docker-compose format v1 which doesn't allow containers to talk to each other by a hostname.
I know it doesn't matter too much for this project, but it's still generally helpful when debugging.
> Use docker-compose v3

- config.go
- ferry.go
If `EnablePProf` is true in the config, the pprof will be available at `localhost:6060/debug/pprof`.
> Enable pprof conditionally

- batch_writer.go
- copydb/test/copydb_test.go
- inline_verifier.go
- sharding/test/primary_key_table_test.go
- test/integration/inline_verifier_test.rb
- test/integration/interrupt_resume_test.rb
This logs the checksum of the failed rows, so we can better debug what happened.
> Log checksum in case of inline verification failure
